{application,porcelain,
             [{description,"Porcelain implements a saner approach to launching and communicating with external OS processes from Elixir. Built on top of Erlang's ports, it provides richer functionality and simpler API."},
              {modules,['Elixir.Porcelain','Elixir.Porcelain.App',
                        'Elixir.Porcelain.Driver.Basic',
                        'Elixir.Porcelain.Driver.Common',
                        'Elixir.Porcelain.Driver.Common.StreamServer',
                        'Elixir.Porcelain.Driver.Goon',
                        'Elixir.Porcelain.Init','Elixir.Porcelain.Process',
                        'Elixir.Porcelain.Result',
                        'Elixir.Porcelain.UsageError']},
              {registered,[]},
              {vsn,"2.0.3"},
              {applications,[kernel,stdlib,elixir,logger,crypto]},
              {mod,{'Elixir.Porcelain.App',[]}}]}.
